

stages:
  - test
  - testAVX
  - testVAES
  - testVAESF
  - test11
  - test17
  - test21


test-java-code:
  stage: test
  script:
    - "ecr_login"
    - "ecr_pull vm_base_intel latest"
    - "ci_docker_run \"vm_base_intel:latest\" bc-lts-java  \"/workspace/bc-lts-java/ci/test_java.sh\""
  artifacts:
    when: always
    reports:
      junit:
      - "core/build/test-results/test/**/TEST-*.xml"
      - "prov/build/test-results/test/**/TEST-*.xml"
      - "jmail/build/test-results/test/**/TEST-*.xml"
      - "pg/build/test-results/test/**/TEST-*.xml"
      - "pkix/build/test-results/test/**/TEST-*.xml"
      - "mail/build/test-results/test/**/TEST-*.xml"
      - "util/build/test-results/test/**/TEST-*.xml"
      - "tls/build/test-results/test/**/TEST-*.xml"

test-code-avx:
  stage: testAVX
  script:
    - "ecr_login"
    - "ecr_pull vm_base_intel latest"
    - "ci_docker_run \"vm_base_intel:latest\" bc-lts-java \"/workspace/bc-lts-java/ci/test_avx.sh\""
  artifacts:
    when: always
    reports:
      junit:
        - "core/build/test-results/testAVX/**/TEST-*.xml"
        - "prov/build/test-results/testAVX/**/TEST-*.xml"
        - "jmail/build/test-results/testAVX/**/TEST-*.xml"
        - "pg/build/test-results/testAVX/**/TEST-*.xml"
        - "pkix/build/test-results/testAVX/**/TEST-*.xml"
        - "mail/build/test-results/testAVX/**/TEST-*.xml"
        - "util/build/test-results/testAVX/**/TEST-*.xml"
        - "tls/build/test-results/testAVX/**/TEST-*.xml"


test-code-vaes:
  stage: testVAES
  script:
    - "ecr_login"
    - "ecr_pull vm_base_intel latest"
    - "ci_docker_run \"vm_base_intel:latest\" bc-lts-java \"/workspace/bc-lts-java/ci/test_vaes.sh\""
  artifacts:
    when: always
    reports:
      junit:
        - "core/build/test-results/testVAES/**/TEST-*.xml"
        - "prov/build/test-results/testVAES/**/TEST-*.xml"
        - "jmail/build/test-results/testVAES/**/TEST-*.xml"
        - "pg/build/test-results/testVAES/**/TEST-*.xml"
        - "pkix/build/test-results/testVAES/**/TEST-*.xml"
        - "mail/build/test-results/testVAES/**/TEST-*.xml"
        - "util/build/test-results/testVAES/**/TEST-*.xml"
        - "tls/build/test-results/testVAES/**/TEST-*.xml"



test-code-vaesf:
  stage: testVAESF
  script:
    - "ecr_login"
    - "ecr_pull vm_base_intel latest"
    - "ci_docker_run \"vm_base_intel:latest\" bc-lts-java \"/workspace/bc-lts-java/ci/test_vaesf.sh\""
  artifacts:
    when: always
    reports:
      junit:
        - "core/build/test-results/testVAESF/**/TEST-*.xml"
        - "prov/build/test-results/testVAESF/**/TEST-*.xml"
        - "jmail/build/test-results/testVAESF/**/TEST-*.xml"
        - "pg/build/test-results/testVAESF/**/TEST-*.xml"
        - "pkix/build/test-results/testVAESF/**/TEST-*.xml"
        - "mail/build/test-results/testVAESF/**/TEST-*.xml"
        - "util/build/test-results/testVAESF/**/TEST-*.xml"
        - "tls/build/test-results/testVAESF/**/TEST-*.xml"


test-java11-code:
  stage: test11
  script:
    - "ecr_login"
    - "ecr_pull vm_base_intel latest"
    - "ci_docker_run \"vm_base_intel:latest\"  bc-lts-java \"/workspace/bc-lts-java/ci/test_jvms_11.sh\""

  artifacts:
    when: always
    reports:
      junit: build/artifacts/jdk11/reports/xml/**/TEST-*.xml


test-java17-code:
  stage: test17
  script:
    - "ecr_login"
    - "ecr_pull vm_base_intel latest"
    - "ci_docker_run \"vm_base_intel:latest\" bc-lts-java \"/workspace/bc-lts-java/ci/test_jvms_17.sh\""

  artifacts:
    when: always
    reports:
      junit: build/artifacts/jdk17/reports/xml/**/TEST-*.xml


test-java21-code:
  stage: test21
  script:
    - "ecr_login"
    - "ecr_pull vm_base_intel latest"
    - "ci_docker_run \"vm_base_intel:latest\" bc-lts-java \"/workspace/bc-lts-java/ci/test_jvms_21.sh\""

  artifacts:
    when: always
    reports:
      junit: build/artifacts/jdk21/reports/xml/**/TEST-*.xml
  

