stages:
  - test
  - testSSE
  - testAVX
  - testVAES



test-java-code:
  stage: test
  script:
    - "apply_overlay bc-java ./"
    - . cienv-11.sh
    - "./gradlew clean withNative prov:build util:build pg:build pkix:build tls:build mail:build"

test-code-sse:
  stage: testSSE
  script:
    - "apply_overlay bc-java ./"
    - "rm -rf /tmp/bcfipslibs"
    - "mkdir -p /tmp/bcfipslibs"
    - . cienv-11.sh
    - "./gradlew clean core:compileJava; \ cd native; \ ./build_linux.sh; \ cd .."
    - "./gradlew clean withNative prov:build util:build pg:build pkix:build tls:build mail:build copyJars -x test"
    - "tmpLibDir=$(mktemp -d -t bc-libs-XXXXXXXXXX)"
    - "export LD_LIBRARY_PATH=\"$LD_LIBRARY_PATH:$tmpLibDir\""
    - "java -Dorg.bouncycastle.native.cpu_variant=linux-x86_64-sse -cp jars/bcprov-lts8on-1.0.0-SNAPSHOT.jar org.bouncycastle.util.DumpInfo"
    - "./gradlew -Pskip.pqc.tests testSSE  -x test"


test-code-avx:
  stage: testAVX
  script:
    - "apply_overlay bc-java ./"
    - "rm -rf /tmp/bcfipslibs"
    - "mkdir -p /tmp/bcfipslibs"
    - . cienv-11.sh
    - "./gradlew clean core:compileJava; \ cd native; \ ./build_linux.sh; \ cd .."
    - "./gradlew clean withNative prov:build util:build pg:build pkix:build tls:build mail:build copyJars -x test"
    - "tmpLibDir=$(mktemp -d -t bc-libs-XXXXXXXXXX)"
    - "export LD_LIBRARY_PATH=\"$LD_LIBRARY_PATH:$tmpLibDir\""
    - "java -Dorg.bouncycastle.native.cpu_variant=linux-x86_64-avx -cp jars/bcprov-lts8on-1.0.0-SNAPSHOT.jar org.bouncycastle.util.DumpInfo"
    - "./gradlew -Pskip.pqc.tests testAVX  -x test"

test-code-vaes:
  stage: testVAES
  script:
    - "apply_overlay bc-java ./"
    - "rm -rf /tmp/bcfipslibs"
    - "mkdir -p /tmp/bcfipslibs"
    - . cienv-11.sh
    - "./gradlew clean core:compileJava; \ cd native; \ ./build_linux.sh; \ cd .."
    - "./gradlew clean withNative prov:build util:build pg:build pkix:build tls:build mail:build copyJars -x test"
    - "tmpLibDir=$(mktemp -d -t bc-libs-XXXXXXXXXX)"
    - "export LD_LIBRARY_PATH=\"$LD_LIBRARY_PATH:$tmpLibDir\""
    - "java -Dorg.bouncycastle.native.cpu_variant=linux-x86_64-vaes -cp jars/bcprov-lts8on-1.0.0-SNAPSHOT.jar org.bouncycastle.util.DumpInfo"
    - "./gradlew -Pskip.pqc.tests testVAES  -x test"
