stages:
  - test
  - testAVX
  - testVAES
  - testVAESF


test-java-code:
  stage: test
  script:
    - "/usr/sbin/ifconfig"
    - "apply_overlay bc-java ./"
    - "sh gettestdata.sh"
    - . cienv-11.sh
    - "./gradlew clean cleanNative withNative build"


test-code-avx:
  stage: testAVX
  script:
    - "apply_overlay bc-java ./"
    - "sh gettestdata.sh"
    - "rm -rf /tmp/bcfipslibs"
    - "mkdir -p /tmp/bcfipslibs"
    - . cienv-11.sh
    - "./gradlew clean core:compileJava; cd native_c; ./build_linux.sh;  cd .."
    - "./gradlew clean cleanNative withNative build -x test"
    - "tmpLibDir=$(mktemp -d -t bc-jni-libs-XXXXXXXXXX)"
    - "export LD_LIBRARY_PATH=\"$LD_LIBRARY_PATH:$tmpLibDir\""
    - "java -Dorg.bouncycastle.native.cpu_variant=avx -cp prov/build/libs/bcprov-lts8on-`./version.sh`.jar org.bouncycastle.util.DumpInfo"
    - "./gradlew -Pskip.pqc.tests testAVX  -x test"

test-code-vaes:
  stage: testVAES
  script:
    - "apply_overlay bc-java ./"
    - "sh gettestdata.sh"
    - "rm -rf /tmp/bcfipslibs"
    - "mkdir -p /tmp/bcfipslibs"
    - . cienv-11.sh
    - "./gradlew clean core:compileJava; cd native_c; ./build_linux.sh; cd .."
    - "./gradlew clean cleanNative withNative build -x test"
    - "tmpLibDir=$(mktemp -d -t bc-jni-libs-XXXXXXXXXX)"
    - "export LD_LIBRARY_PATH=\"$LD_LIBRARY_PATH:$tmpLibDir\""
    - "java -Dorg.bouncycastle.native.cpu_variant=vaes -cp prov/build/libs/bcprov-lts8on-`./version.sh`.jar org.bouncycastle.util.DumpInfo"
    - "./gradlew -Pskip.pqc.tests testVAES  -x test"

test-code-vaesf:
  stage: testVAESF
  script:
    - "apply_overlay bc-java ./"
    - "sh gettestdata.sh"
    - "rm -rf /tmp/bcfipslibs"
    - "mkdir -p /tmp/bcfipslibs"
    - . cienv-11.sh
    - "./gradlew clean core:compileJava;  cd native_c; ./build_linux.sh; cd .."
    - "./gradlew clean cleanNative withNative build -x test"
    - "tmpLibDir=$(mktemp -d -t bc-jni-libs-XXXXXXXXXX)"
    - "export LD_LIBRARY_PATH=\"$LD_LIBRARY_PATH:$tmpLibDir\""
    - "java -Dorg.bouncycastle.native.cpu_variant=vaesf -cp prov/build/libs/bcprov-lts8on-`./version.sh`.jar org.bouncycastle.util.DumpInfo"
    - "./gradlew -Pskip.pqc.tests testVAESF  -x test"
