

stages:
  - test
  - testAVX
  - testVAES
  - testVAESF
  - test11
  - test17
  - test21


test-java-code:
  stage: test
  script:
    - "ecr_login"
    - "ecr_pull vm_base_intel latest"
    - "docker run -i -u $(id -u):$(id -g) --rm --pull=missing --cpus=1.5 -v `pwd`:/workspace/bc-lts-java \"489290151264.dkr.ecr.ap-southeast-2.amazonaws.com/vm_base_intel:latest\" /bin/bash \"/workspace/bc-lts-java/ci/test_java.sh\""
  artifacts:
    when: always
    paths:
      - "core/build/reports"
      - "prov/build/reports"
      - "jmail/build/reports"
      - "pg/build/reports"
      - "pkix/build/reports"
      - "mail/build/reports"
      - "util/build/reports"
      - "tls/build/reports"

test-code-avx:
  stage: testAVX
  script:
    - "ecr_login"
    - "ecr_pull vm_base_intel latest"
    - "docker run -i -u $(id -u):$(id -g) --rm --pull=missing --cpus=1.5 -v `pwd`:/workspace/bc-lts-java \"489290151264.dkr.ecr.ap-southeast-2.amazonaws.com/vm_base_intel:latest\" /bin/bash \"/workspace/bc-lts-java/ci/test_avx.sh\""

test-code-vaes:
  stage: testVAES
  script:
    - "ecr_login"
    - "ecr_pull vm_base_intel latest"
    - "docker run -i -u $(id -u):$(id -g) --rm --pull=missing --cpus=1.5 -v `pwd`:/workspace/bc-lts-java \"489290151264.dkr.ecr.ap-southeast-2.amazonaws.com/vm_base_intel:latest\" /bin/bash \"/workspace/bc-lts-java/ci/test_vaes.sh\""


test-code-vaesf:
  stage: testVAESF
  script:
    - "ecr_login"
    - "ecr_pull vm_base_intel latest"
    - "docker run -i -u $(id -u):$(id -g) --rm --pull=missing --cpus=1.5 -v `pwd`:/workspace/bc-lts-java \"489290151264.dkr.ecr.ap-southeast-2.amazonaws.com/vm_base_intel:latest\" /bin/bash \"/workspace/bc-lts-java/ci/test_vaesf.sh\""


test-java11-code:
  stage: test11
  script:
    - "ecr_login"
    - "ecr_pull vm_base_intel latest"
    - "docker run -i -u $(id -u):$(id -g) --rm --pull=missing --cpus=1.5 -v `pwd`:/workspace/bc-lts-java \"489290151264.dkr.ecr.ap-southeast-2.amazonaws.com/vm_base_intel:latest\" /bin/bash \"/workspace/bc-lts-java/ci/test_jvms_11.sh\""

  artifacts:
    when: always
    reports:
      junit: build/artifacts/jdk11/reports/xml/**/TEST-*.xml


test-java17-code:
  stage: test17
  script:
    - "ecr_login"
    - "ecr_pull vm_base_intel latest"
    - "docker run -i -u $(id -u):$(id -g) --rm --pull=missing --cpus=1.5 -v `pwd`:/workspace/bc-lts-java \"489290151264.dkr.ecr.ap-southeast-2.amazonaws.com/vm_base_intel:latest\" /bin/bash \"/workspace/bc-lts-java/ci/test_jvms_17.sh\""

  artifacts:
    when: always
    reports:
      junit: build/artifacts/jdk17/reports/xml/**/TEST-*.xml


test-java21-code:
  stage: test21
  script:
    - "ecr_login"
    - "ecr_pull vm_base_intel latest"
    - "docker run -i -u $(id -u):$(id -g) --rm --pull=missing --cpus=1.5 -v `pwd`:/workspace/bc-lts-java \"489290151264.dkr.ecr.ap-southeast-2.amazonaws.com/vm_base_intel:latest\" /bin/bash \"/workspace/bc-lts-java/ci/test_jvms_21.sh\""

  artifacts:
    when: always
    reports:
      junit: build/artifacts/jdk21/reports/xml/**/TEST-*.xml
  

