stages:
  - test
  - testSSE
  - testAVX



test-java-code:
  stage: test
  script:
    - "apply_overlay bc-fips-2-0-X-java ./"
    - . cienv.sh
    - "gradle clean build copyJars"

test-code-sse:
  stage: testSSE
  script:
    - "apply_overlay bc-fips-2-0-X-java ./"
    - "rm -rf /tmp/bcfipslibs"
    - "mkdir -p /tmp/bcfipslibs"
    - . cienv.sh
    - "gradle clean compileJava; \ cd native; \ ./build_linux.sh; \ cd .."
    - "gradle withNative build copyJars  -x test"
    - "tmpLibDir=$(mktemp -d -t bc-libs-XXXXXXXXXX)"
    - "export LD_LIBRARY_PATH=\"$LD_LIBRARY_PATH:$tmpLibDir\""
    - "java -Dorg.bouncycastle.native.cpu_variant=linux-x86_64-sse -cp jars/bc-fips-2.0.1-SNAPSHOT.jar org.bouncycastle.util.DumpInfo -verbose"
    - "gradle clean withNative build copyJars testSSE  -x test"


test-code-avx:
  stage: testAVX
  script:
    - "apply_overlay bc-fips-2-0-X-java ./"
    - "rm -rf /tmp/bcfipslibs"
    - "mkdir -p /tmp/bcfipslibs"
    - . cienv.sh
    - "gradle clean compileJava; \ cd native; \ ./build_linux.sh; \ cd .."
    - "gradle withNative build copyJars  -x test"
    - "tmpLibDir=$(mktemp -d -t bc-libs-XXXXXXXXXX)"
    - "export LD_LIBRARY_PATH=\"$LD_LIBRARY_PATH:$tmpLibDir\""
    - "java -Dorg.bouncycastle.native.cpu_variant=linux-x86_64-avx -cp jars/bc-fips-2.0.1-SNAPSHOT.jar org.bouncycastle.util.DumpInfo -verbose"
    - "gradle clean withNative build copyJars testAVX  -x test"

